/*
 *            Copyright 2009-2026 The VOTCA Development Team
 *                       (http://www.votca.org)
 *
 *      Licensed under the Apache License, Version 2.0 (the "License")
 *
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *              http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#pragma once
#ifndef VOTCA_XTP_EWALDSHAPECORRECTION_H
#define VOTCA_XTP_EWALDSHAPECORRECTION_H

// Local VOTCA includes
#include "eeinteractor.h"
#include "eigen.h"
#include "ewaldregistry.h"

/**
 * \brief Shape/surface term of a 3D Ewald sum: the uniform depolarizing
 *        field arising from the boundary condition applied at the edge of
 *        an infinite periodic sum, expressed via the total system dipole
 *        moment.
 *
 * Derived from scratch (De Leeuw, Perram & Smith 1980's standard result for
 * the order-of-summation-dependent "surface term" of a conditionally
 * convergent dipole lattice sum), not ported from the legacy code, though
 * the resulting depolarization factors were cross-checked against it and
 * do match: 4*pi/(3*V) for an isotropic (cube/sphere) boundary, or
 * 4*pi/V acting on the z-component only for a slab (2D-periodic, z-normal)
 * boundary -- both under the vacuum-boundary convention (surrounding
 * dielectric constant = 1; a general surrounding-medium factor is not
 * implemented here since the legacy code's own use of it was always at
 * this vacuum default).
 *
 *   M = sum_j (q_j * r_j + mu_j)          (total system dipole moment)
 *   E = -(4*pi / (3*V)) * M                (cube/sphere)
 *   E = -(4*pi / V) * M_z * z_hat          (slab)
 *
 * Unlike EwaldRealSpaceSum/EwaldReciprocalSpaceSum, this is not an
 * intermolecular-only sum: M includes every registered segment, including
 * the target's own. The depolarizing field is a mean-field property of the
 * whole sample's own surface polarization acting back on itself (the same
 * way a uniformly polarized dielectric sphere experiences its own
 * depolarizing field), not a pairwise molecule-molecule interaction, so
 * there is no analogous self-interaction to exclude.
 *
 * Units: bohr, Hartree atomic units throughout.
 */

namespace votca {
namespace xtp {

enum class EwaldShape { Cube, Slab };

class EwaldShapeCorrection {
 public:
  EwaldShapeCorrection(double volume, const EwaldRegistry& registry,
                       EwaldShape shape);

  // Adds the (position-independent) depolarizing field into target's own
  // V()/V_noE() accumulator, generated by every segment in the registry
  // at charge state source_state (including target's own segment, if
  // registered -- see class documentation).
  template <enum Estatic CE>
  void AddFieldAt(PolarSite& target, EwaldChargeState source_state) const;

 private:
  Eigen::Vector3d TotalDipoleMoment(EwaldChargeState source_state) const;

  double volume_;
  const EwaldRegistry& registry_;
  EwaldShape shape_;
};

}  // namespace xtp
}  // namespace votca

#endif  // VOTCA_XTP_EWALDSHAPECORRECTION_H
