ROOTDIR := $(shell cat ../../trunc)

JPGPICS :=
PNGPICS := 
FIGPICS := 
AGRPICS :=
GPPICS  := 
SVGPICS := marcus_parabolas.eps monomer_parabolas.eps
SUBDIRS :=
LOCALCLEAN :=

include ../../Makefile.incl

