name: Make Release
on:
  push:
    tags:
    - 'v[1-9]*'

jobs:
  release:
    name: Make Release
    if: github.repository_owner == 'votca'
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.VOTCA_BOT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, 'rc') }}
      - name: Get version
        run: echo "::set-env name=VERSION::${GITHUB_REF#refs/tags/v}"
      - name: Upload manual
        uses: actions/upload-release-asset@v1
      - name: Get manual
        run: wget https://github.com/votca/votca/releases/download/v${{ env.VERSION }}/votca-csg-manual-${{ env.VERSION }}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.VOTCA_BOT_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./votca-csg-manual-${{ env.VERSION }}.pdf
          asset_name: votca-csg-manual-${{ env.VERSION }}.pdf
          asset_content_type: application/pdf
