# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mashaya1/Research/My_Votca/src/csg

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mashaya1/Research/My_Votca/src/csg

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mashaya1/Research/My_Votca/src/csg/CMakeFiles /home/mashaya1/Research/My_Votca/src/csg/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mashaya1/Research/My_Votca/src/csg/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named manpages

# Build rule for target.
manpages: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 manpages
.PHONY : manpages

# fast build rule for target.
manpages/fast:
	$(MAKE) -f CMakeFiles/manpages.dir/build.make CMakeFiles/manpages.dir/build
.PHONY : manpages/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named csg_call

# Build rule for target.
csg_call: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_call
.PHONY : csg_call

# fast build rule for target.
csg_call/fast:
	$(MAKE) -f scripts/CMakeFiles/csg_call.dir/build.make scripts/CMakeFiles/csg_call.dir/build
.PHONY : csg_call/fast

#=============================================================================
# Target rules for targets named csg_inverse

# Build rule for target.
csg_inverse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_inverse
.PHONY : csg_inverse

# fast build rule for target.
csg_inverse/fast:
	$(MAKE) -f scripts/CMakeFiles/csg_inverse.dir/build.make scripts/CMakeFiles/csg_inverse.dir/build
.PHONY : csg_inverse/fast

#=============================================================================
# Target rules for targets named help2t2t

# Build rule for target.
help2t2t: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 help2t2t
.PHONY : help2t2t

# fast build rule for target.
help2t2t/fast:
	$(MAKE) -f scripts/CMakeFiles/help2t2t.dir/build.make scripts/CMakeFiles/help2t2t.dir/build
.PHONY : help2t2t/fast

#=============================================================================
# Target rules for targets named multi_g_rdf

# Build rule for target.
multi_g_rdf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 multi_g_rdf
.PHONY : multi_g_rdf

# fast build rule for target.
multi_g_rdf/fast:
	$(MAKE) -f scripts/CMakeFiles/multi_g_rdf.dir/build.make scripts/CMakeFiles/multi_g_rdf.dir/build
.PHONY : multi_g_rdf/fast

#=============================================================================
# Target rules for targets named gmx_print_version

# Build rule for target.
gmx_print_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmx_print_version
.PHONY : gmx_print_version

# fast build rule for target.
gmx_print_version/fast:
	$(MAKE) -f src/libcsg/CMakeFiles/gmx_print_version.dir/build.make src/libcsg/CMakeFiles/gmx_print_version.dir/build
.PHONY : gmx_print_version/fast

#=============================================================================
# Target rules for targets named hgversion

# Build rule for target.
hgversion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hgversion
.PHONY : hgversion

# fast build rule for target.
hgversion/fast:
	$(MAKE) -f src/libcsg/CMakeFiles/hgversion.dir/build.make src/libcsg/CMakeFiles/hgversion.dir/build
.PHONY : hgversion/fast

#=============================================================================
# Target rules for targets named votca_csg

# Build rule for target.
votca_csg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 votca_csg
.PHONY : votca_csg

# fast build rule for target.
votca_csg/fast:
	$(MAKE) -f src/libcsg/CMakeFiles/votca_csg.dir/build.make src/libcsg/CMakeFiles/votca_csg.dir/build
.PHONY : votca_csg/fast

#=============================================================================
# Target rules for targets named csg_density

# Build rule for target.
csg_density: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_density
.PHONY : csg_density

# fast build rule for target.
csg_density/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_density.dir/build.make src/tools/CMakeFiles/csg_density.dir/build
.PHONY : csg_density/fast

#=============================================================================
# Target rules for targets named csg_dump

# Build rule for target.
csg_dump: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_dump
.PHONY : csg_dump

# fast build rule for target.
csg_dump/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_dump.dir/build.make src/tools/CMakeFiles/csg_dump.dir/build
.PHONY : csg_dump/fast

#=============================================================================
# Target rules for targets named csg_fmatch

# Build rule for target.
csg_fmatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_fmatch
.PHONY : csg_fmatch

# fast build rule for target.
csg_fmatch/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_fmatch.dir/build.make src/tools/CMakeFiles/csg_fmatch.dir/build
.PHONY : csg_fmatch/fast

#=============================================================================
# Target rules for targets named csg_gmxtopol

# Build rule for target.
csg_gmxtopol: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_gmxtopol
.PHONY : csg_gmxtopol

# fast build rule for target.
csg_gmxtopol/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_gmxtopol.dir/build.make src/tools/CMakeFiles/csg_gmxtopol.dir/build
.PHONY : csg_gmxtopol/fast

#=============================================================================
# Target rules for targets named csg_imcrepack

# Build rule for target.
csg_imcrepack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_imcrepack
.PHONY : csg_imcrepack

# fast build rule for target.
csg_imcrepack/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_imcrepack.dir/build.make src/tools/CMakeFiles/csg_imcrepack.dir/build
.PHONY : csg_imcrepack/fast

#=============================================================================
# Target rules for targets named csg_map

# Build rule for target.
csg_map: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_map
.PHONY : csg_map

# fast build rule for target.
csg_map/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_map.dir/build.make src/tools/CMakeFiles/csg_map.dir/build
.PHONY : csg_map/fast

#=============================================================================
# Target rules for targets named csg_property

# Build rule for target.
csg_property: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_property
.PHONY : csg_property

# fast build rule for target.
csg_property/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_property.dir/build.make src/tools/CMakeFiles/csg_property.dir/build
.PHONY : csg_property/fast

#=============================================================================
# Target rules for targets named csg_resample

# Build rule for target.
csg_resample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_resample
.PHONY : csg_resample

# fast build rule for target.
csg_resample/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_resample.dir/build.make src/tools/CMakeFiles/csg_resample.dir/build
.PHONY : csg_resample/fast

#=============================================================================
# Target rules for targets named csg_stat

# Build rule for target.
csg_stat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_stat
.PHONY : csg_stat

# fast build rule for target.
csg_stat/fast:
	$(MAKE) -f src/tools/CMakeFiles/csg_stat.dir/build.make src/tools/CMakeFiles/csg_stat.dir/build
.PHONY : csg_stat/fast

#=============================================================================
# Target rules for targets named csg_boltzmann

# Build rule for target.
csg_boltzmann: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_boltzmann
.PHONY : csg_boltzmann

# fast build rule for target.
csg_boltzmann/fast:
	$(MAKE) -f src/csg_boltzmann/CMakeFiles/csg_boltzmann.dir/build.make src/csg_boltzmann/CMakeFiles/csg_boltzmann.dir/build
.PHONY : csg_boltzmann/fast

#=============================================================================
# Target rules for targets named html

# Build rule for target.
html: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 html
.PHONY : html

# fast build rule for target.
html/fast:
	$(MAKE) -f share/doc/CMakeFiles/html.dir/build.make share/doc/CMakeFiles/html.dir/build
.PHONY : html/fast

#=============================================================================
# Target rules for targets named csg_include_links

# Build rule for target.
csg_include_links: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 csg_include_links
.PHONY : csg_include_links

# fast build rule for target.
csg_include_links/fast:
	$(MAKE) -f share/template/CMakeFiles/csg_include_links.dir/build.make share/template/CMakeFiles/csg_include_links.dir/build
.PHONY : csg_include_links/fast

#=============================================================================
# Target rules for targets named template_serial

# Build rule for target.
template_serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 template_serial
.PHONY : template_serial

# fast build rule for target.
template_serial/fast:
	$(MAKE) -f share/template/CMakeFiles/template_serial.dir/build.make share/template/CMakeFiles/template_serial.dir/build
.PHONY : template_serial/fast

#=============================================================================
# Target rules for targets named template_threaded

# Build rule for target.
template_threaded: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 template_threaded
.PHONY : template_threaded

# fast build rule for target.
template_threaded/fast:
	$(MAKE) -f share/template/CMakeFiles/template_threaded.dir/build.make share/template/CMakeFiles/template_threaded.dir/build
.PHONY : template_threaded/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... manpages"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... csg_call"
	@echo "... csg_inverse"
	@echo "... help2t2t"
	@echo "... multi_g_rdf"
	@echo "... gmx_print_version"
	@echo "... hgversion"
	@echo "... votca_csg"
	@echo "... csg_density"
	@echo "... csg_dump"
	@echo "... csg_fmatch"
	@echo "... csg_gmxtopol"
	@echo "... csg_imcrepack"
	@echo "... csg_map"
	@echo "... csg_property"
	@echo "... csg_resample"
	@echo "... csg_stat"
	@echo "... csg_boltzmann"
	@echo "... html"
	@echo "... csg_include_links"
	@echo "... template_serial"
	@echo "... template_threaded"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

