#! /bin/bash

if [ "$1" = "--help" ]; then
   echo This is a wrapper to convert potential to gromacs
   echo Usage: ${0##*/}
   exit 0
fi

if [ ${#atoms[@]} -eq 0 ]; then
   echo Could not get atomname for \$atoms > /dev/stdout
   exit 1
fi

if [ $(type -t run_or_exit) != "function" ]; then
   echo Could not find function run_or_exit > /dev/stdout
   exit 1
fi

run_or_exit --log log_table_to_xvg_${atom1}_${atom2} ../table_to_xvg.pl table_${atom1}_${atom2}_new.d table_${atom1}_${atom2}_new.xvg
