name: Copyright
on:
  issue_comment:
    types: [created]
jobs:
  edit:
    name: Copyright
    if: ${{ github.event.comment.body == '@votca-bot copyright' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check if message comes from PR
        uses: octokit/request-action@v2.x
        id: issue_info
        with:
          route: GET /repos/:repository/issues/:pull_number
          repository: ${{ github.repository }}
          pull_number: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get PR info
        if: ${{ fromJSON(steps.issue_info.outputs.data).pull_request }}
        uses: octokit/request-action@v2.x
        id: pr_info
        with:
          route: GET /repos/:repository/pulls/:pull_number
          repository: ${{ github.repository }}
          pull_number: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout head branch from PR
        if: ${{ fromJSON(steps.issue_info.outputs.data).pull_request }}
        uses: actions/checkout@v2
        with:
          repository: ${{ fromJSON(steps.pr_info.outputs.data).head.repo.full_name }}
          ref: ${{ fromJSON(steps.pr_info.outputs.data).head.ref }}
          fetch-depth: 0
          token: ${{ secrets.VOTCA_BOT_TOKEN }}
      - name: Create and commit copyright updates
        if: ${{ fromJSON(steps.issue_info.outputs.data).pull_request }}
        uses: votca/actions/copyright@master
        with:
          base: ${{ fromJSON(steps.pr_info.outputs.data).base.sha }}
