name: Make Release
on:
  push:
    tags:
    - 'v[1-9]*'

jobs:
  release:
    name: Make Release
    if: github.repository_owner == 'votca'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Changlog
        uses: votca/actions/release_changelog@master
        with:
          version: ${{ github.ref }}
          changelog: 'release_changelog.md'
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.VOTCA_BOT_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ contains(github.ref, 'rc') }}
          body_path: 'release_changelog.md'
