name: Forward
on:
  push:
    branches:
      - master
      - stable

jobs:
  VOTCA:
    if: github.repository_owner == 'votca'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: votca/votca
          ref: master
          fetch-depth: 0
          token: ${{ secrets.VOTCA_BOT_TOKEN }}
      - name: Update submodule
        uses: votca/actions/forward@master
        with:
          module: ${{ github.repository }}
