include(CMakeFindDependencyMacro)
find_dependency(Eigen3)
find_dependency(Boost 1.53.0 COMPONENTS program_options)
find_dependency(VOTCA_TOOLS NO_MODULE)
include("${CMAKE_CURRENT_LIST_DIR}/VOTCA_CSG_Targets.cmake")
