#!/bin/bash -e

CALCULATOR_SRC="../../../md2qm/src/libmd2qm/calculators"
OUT="$PWD/all.tex"

if [ ! -d $CALCULATOR_SRC ]; then
  echo "error: calculator directory not found"
fi

cd $CALCULATOR_SRC

echo "running doxygen"

doxygen -g > doxygen.log 2>&1
doxygen >> doxygen.log 2>&1

echo "done with doxygen"

echo "% THIS FILE IS AUTOMATICALLY GENERATED, DO NOT TOUCH!!!" > $OUT

for file in latex/*.tex; do
  name=$(sed -ne '/\\subsection{Detailed Description}/,/\\subsection/p' $file | awk '/Callname/{print $2}')
  if [ ! -z "$name" ]; then
    echo "Generating documentation for calculator $name from $file"
    echo "\subsubsection{$name}" >> $OUT
    echo "\label{calc:$name}" >> $OUT
    sed -ne '/\\subsection{Detailed Description}/,/\\subsection/p' $file | \
      sed -e '1d' -e '$d' \
      -e '/The documentation for this class was generated from the following/,$d' \
      -e '/Callname/d' \
      -e 's/DoxyItemize/itemize/' >> $OUT
  fi
done



