 # a variable named `cutoff` is required by GROMOS_54A7_ATB.lt
 variable cutoff equal 14.0 # Angstroms
        units real
        atom_style      full
        bond_style      harmonic
        angle_style     harmonic
        dihedral_style  harmonic
        improper_style  harmonic
        pair_style      lj/cut/coul/cut ${cutoff}
       #pair_style      lj/cut/coul/long   ${cutoff}
        special_bonds lj 0.0 0.0 0.5 coul 0.0 0.0 1.0 angle yes dihedral yes
