#! /bin/bash

#if not defined try to parse agrument
if [ -z "${CSGSHARE}" ]; then
   echo "Error: Environment values CSGSHARE not defined" >&2
   echo "Try ${0##*/} --help for help" >&2
   exit 1
fi

#echo \$CSGSHARE is ${CSGSHARE}

if [ -f ${CSGSHARE}/scripts/inverse/inverse.sh ]; then
   exec ${CSGSHARE}/scripts/inverse/inverse.sh $@
   exit 0
else
   echo ${0##*/}: Could not run ${CSGSHARE}/scripts/inverse/inverse.sh $@
   exit 1
fi
