#!/bin/bash

#if not defined try to parse agrument
if [ -z "${CSGSHARE}" ]; then
   echo Error: Environment values CSGSHARE not defined 1>&2
   exit 1
fi

echo \$CSGSHARE is ${CSGSHARE}

if [ -f ${CSGSHARE}/scripts/inverse/inverse.sh ]; then
   exec ${CSGSHARE}/scripts/inverse/inverse.sh $@
   exit 0
else
   echo ${0##*/}: Could not run ${CSGSHARE}/scripts/inverse/inverse.sh $@
   exit 1
fi

export CSGINVERSE=$CSGSHARE/scripts/inverse
export SOURCE_WRAPPER=$CSGINVERSE/source_wrapper.pl
export CSGLOG=log.tmp
source $($SOURCE_WRAPPER functions common) || die "$SOURCE_WRAPPER functions common failed" 

script=$($SOURCE_WRAPPER $1 $2)

echo running $script

do_external $@
