#! /usr/bin/env python
VERSION='1.3-dev hgid: 5be923f94811+'
import sys
import os
import getpass
import socket
import commands as cmds
import numpy as np
import xml.dom.minidom as xmld
import time
import argparse
import re
import math
import sqlite3

PROGTITLE = 'THE VOTCA::CTP STATE-FILE UPDATER FOR EXCITON EXTENSION'
PROGDESCR = 'Updates the state file for singlets and triplets +'
VOTCAHEADER = '''\
==================================================
========   VOTCA (http://www.votca.org)   ========
==================================================

{progtitle}

please submit bugs to bugs@votca.org 
ctp_update, version {version}

'''.format(version=VERSION, progtitle=PROGTITLE)

def okquit(what=''):
	if what != '': print what
	sys.exit(0)
def xxquit(what=''):
	if what != '':
		cprint.Error("ERROR: {what}".format(what=what))
	sys.exit(1)
def sysexe(cmd, silent=False, devfile='/dev/null'):
	if VERBOSE: print "{0}@{1}$ {2}".format(USER, HOST, cmd)
	if silent: cmd += ' >> {0} 2>> {0}'.format(devfile)
	cdx = os.system(cmd)
	#SYSCMDS.write('{cmd} = {cdx}\n'.format(cmd=cmd, cdx=cdx))
	return cdx

# =============================================================================
# PROGRAM OPTIONS
# =============================================================================

class CtpHelpFormatter(argparse.HelpFormatter):
	def _format_usage(self, usage, action, group, prefix):
		return VOTCAHEADER
		
progargs = argparse.ArgumentParser(prog='ctp_testsuite',
    formatter_class=lambda prog: CtpHelpFormatter(prog,max_help_position=70),
	description=PROGDESCR)
	
progargs.add_argument('-f', '--file',
    dest='sqlfile',   
    action='store',
    required=False,
    type=str,
	default='',
    help='State file to update.')
    
OPTIONS = progargs.parse_args()
if OPTIONS.sqlfile == '':
	progargs.print_help()
	okquit("\nQuit here, because: State file not set (option -f/--file)")

# =============================================================================
# SQLITE3 EXECUTION
# =============================================================================

conn = sqlite3.connect(OPTIONS.sqlfile)
port = conn.cursor()

try:
	port.execute('ALTER TABLE segments ADD COLUMN UnXnNs DOUBLE PRECISION;')
    port.execute('ALTER TABLE segments ADD COLUMN UnXnNt DOUBLE PRECISION;')
    port.execute('ALTER TABLE segments ADD COLUMN UxNxXs DOUBLE PRECISION;')
    port.execute('ALTER TABLE segments ADD COLUMN UxNxXt DOUBLE PRECISION;')
    port.execute('ALTER TABLE segments ADD COLUMN UxXnNs DOUBLE PRECISION;')
    port.execute('ALTER TABLE segments ADD COLUMN UxXnNs DOUBLE PRECISION;')
    port.execute('ALTER TABLE segments ADD COLUMN eSinglet DOUBLE PRECISION;')
    port.execute('ALTER TABLE segments ADD COLUMN eTriplet DOUBLE PRECISION;')



except:
	print "'segments' table already up-to-date"
	
try:
	port.execute('ALTER TABLE pairs ADD COLUMN IOs DOUBLE PRECISION;')
    port.execute('ALTER TABLE pairs ADD COLUMN IOt DOUBLE PRECISION;')
    port.execute('ALTER TABLE pairs ADD COLUMN has_s DOUBLE PRECISION;')
    port.execute('ALTER TABLE pairs ADD COLUMN has_t DOUBLE PRECISION;')
    port.execute('ALTER TABLE pairs ADD COLUMN rate12s DOUBLE PRECISION;')
    port.execute('ALTER TABLE pairs ADD COLUMN rate21s DOUBLE PRECISION;')
    port.execute('ALTER TABLE pairs ADD COLUMN rate12t DOUBLE PRECISION;')
    port.execute('ALTER TABLE pairs ADD COLUMN rate21t DOUBLE PRECISION;')
    port.execute('ALTER TABLE pairs ADD COLUMN Jeff2s DOUBLE PRECISION;')
    port.execute('ALTER TABLE pairs ADD COLUMN Jeff2t DOUBLE PRECISION;')
except:
	print "'pairs' table already up-to-date"

conn.commit()
conn.close()
sys.exit(0)

