#! /bin/bash -e

die() {
  echo "$*"
  exit 1
}

[[ -z $1 || -z $2 ]] && die "Missing argument"
[[ -f $1 ]] || die "File '$1' not found"
tmp=$(mktemp -d) || die "mktemp failed"

cp $1 $tmp
cd $tmp
f=${1##*/}
latex -halt-on-error "${f}"
latex -halt-on-error "${f}"
f=${f%.*}
dvips -E "${f}.dvi" -o "${f}.eps"

cp ${f}.eps ${2}
cd -
rm -rf $tmp
