/*
 *            Copyright 2009-2024 The VOTCA Development Team
 *                       (http://www.votca.org)
 *
 *      Licensed under the Apache License, Version 2.0 (the "License")
 *
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *              http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Local VOTCA includes
#include "votca/xtp/aoreactionfield.h"
#include "votca/xtp/aopotential.h"
#include "votca/xtp/staticsite.h"

namespace votca {
namespace xtp {

// ---------------------------------------------------------------------------
// Step 1: field of xi_mu at each MM polar-site position
//
// We evaluate the electrostatic field generated by a single aux-basis
// function xi_mu at each MM polar-site position R_alpha:
//
//   E_mu(R_alpha) = -∫ xi_mu(r) (r - R_alpha) / |r - R_alpha|^3 dr
//
// This is done numerically.  The Vxc_Grid is built around the QM molecule
// (using the aux basis for FindSignificantShells) so that aux functions on
// the QM atoms are well-represented.  "xfine" is recommended because aux
// functions can be more contracted than the DFT basis.
//
// The function returns a flat vector of length 3*N_sites containing
// {Ex_0, Ey_0, Ez_0, Ex_1, Ey_1, Ez_1, ...}.
// ---------------------------------------------------------------------------
Eigen::VectorXd AOReactionField::CalcAuxFunctionField(
    const AOShell& shell, Index func_in_shell, const Vxc_Grid& grid,
    const std::vector<PolarSegment>& polar_segs) const {

  // Count total number of polar sites across all segments
  Index n_sites = 0;
  for (const auto& seg : polar_segs) {
    n_sites += seg.size();
  }

  Eigen::VectorXd field = Eigen::VectorXd::Zero(3 * n_sites);

  // Loop over all grid boxes and grid points; accumulate field contributions
  for (Index ibox = 0; ibox < grid.getBoxesSize(); ++ibox) {
    const GridBox& box = grid[ibox];
    const std::vector<Eigen::Vector3d>& points = box.getGridPoints();
    const std::vector<double>& weights = box.getGridWeights();

    for (Index p = 0; p < box.size(); ++p) {
      // Evaluate xi_mu at this grid point.
      // EvalAOspace returns values for all functions in the shell; pick index
      // func_in_shell within that shell.
      AOShell::AOValues ao = shell.EvalAOspace(points[p]);
      double xi_mu = ao.values(func_in_shell) * weights[p];

      if (std::abs(xi_mu) < 1e-15) {
        continue;
      }

      // Accumulate field contribution at each polar site
      Index site_idx = 0;
      for (const auto& seg : polar_segs) {
        for (const auto& site : seg) {
          Eigen::Vector3d r = points[p] - site.getPos();
          double r_norm = r.norm();
          if (r_norm < 1e-10) {
            ++site_idx;
            continue;
          }
          // E = -xi_mu(r)*w * (r - R) / |r - R|^3
          // (negative: electron density contribution to electric field)
          Eigen::Vector3d contrib = -xi_mu * r / (r_norm * r_norm * r_norm);
          field.segment<3>(3 * site_idx) += contrib;
          ++site_idx;
        }
      }
    }
  }
  return field;
}

// ---------------------------------------------------------------------------
// Step 2: potential of induced dipoles -> column mu_idx of (mu|nu)_reac
//
// Given induced dipoles Delta_d_mu stored in polar_segs[].Induced_Dipole(),
// compute the analytic integral:
//
//   (nu|mu)_reac = <xi_nu | V_Delta_d | xi_nu=mu>
//               = sum_alpha Delta_d_mu(alpha) · grad_R <xi_nu|1/|r-R||xi_nu=mu>|_{R_alpha}
//
// We do this by creating a StaticSite at each MM site with zero charge and
// dipole = Delta_d_mu(alpha), then calling AOMultipole::FillPotential which
// analytically evaluates the full Naux x Naux matrix of the combined dipole
// potential.  We then extract column mu_idx from that matrix.
//
// Note: AOMultipole::FillPotential accumulates with a minus sign
// (nuclear convention), so we negate.  See aomultipole.cc FillPotential.
// ---------------------------------------------------------------------------
Eigen::VectorXd AOReactionField::CalcDipolePotentialColumn(
    Index mu_idx, const AOBasis& auxbasis,
    const std::vector<PolarSegment>& polar_segs) const {

  // Build vector of StaticSites with dipole = Delta_d_mu(alpha), charge = 0
  std::vector<std::unique_ptr<StaticSite>> dipole_sites;
  Index site_global_idx = 0;
  for (const auto& seg : polar_segs) {
    for (const auto& site : seg) {
      auto s = std::make_unique<StaticSite>(site_global_idx,
                                           site.getElement(), site.getPos());
      // Q_ layout: Q00, Q11c(x), Q11s(y), Q10(z), Q20, Q21c, Q21s, Q22c, Q22s
      // getDipole() returns Q_.segment<3>(1) = {Q11c, Q11s, Q10} = {x, y, z}
      Vector9d multipole = Vector9d::Zero();
      multipole(0) = 0.0;  // no charge
      const Eigen::Vector3d& d = site.Induced_Dipole();
      multipole(1) = d(0);  // Q11c = x
      multipole(2) = d(1);  // Q11s = y
      multipole(3) = d(2);  // Q10  = z
      s->setMultipole(multipole, 1);
      dipole_sites.push_back(std::move(s));
      ++site_global_idx;
    }
  }

  // AOMultipole::FillPotential with rank-1 sites gives the full Naux x Naux
  // matrix of the dipole potential integrated against all pairs (xi_nu, xi_nu').
  // FillPotential uses -= (nuclear-attraction sign convention), so the
  // matrix represents -<xi_nu | V_dipoles | xi_nu'>.  We negate to get
  // +<xi_nu | V_dipoles | xi_nu'>.
  AOMultipole dip_pot;
  dip_pot.FillPotential(auxbasis, dipole_sites);

  // Extract column mu_idx: this gives (nu | mu)_reac for all nu.
  // Because AOMultipole produces a symmetric matrix (it's a Hermitian operator
  // on the basis), column mu_idx equals row mu_idx, and this is the column of
  // V_reac we want.
  return -dip_pot.Matrix().col(mu_idx);
}

// ---------------------------------------------------------------------------
// Main assembly
// ---------------------------------------------------------------------------
void AOReactionField::Fill(const AOBasis& auxbasis, const QMMolecule& qmatoms,
                           std::vector<PolarSegment>& polar_segs,
                           const std::string& grid_quality) {

  const Index naux = auxbasis.AOBasisSize();
  matrix_ = Eigen::MatrixXd::Zero(naux, naux);

  // --- Build the Vxc_Grid for numerical field integration (step 1) ---
  // We build it around the QM molecule using the aux basis so that all
  // aux-basis functions are well represented on the grid.
  Vxc_Grid grid;
  grid.GridSetup(grid_quality, qmatoms, auxbasis);

  // --- Pre-factor the Thole A matrix once ---
  // Cholesky_IntraSegment does this internally per segment, but for the
  // multi-segment case we need a combined solve.  We replicate the factoring
  // logic: build the full combined A matrix across all segments, factorise
  // once, then solve N_aux right-hand sides.
  //
  // Collect all polar sites into a flat list for the linear system.
  Index n_sites = 0;
  for (const auto& seg : polar_segs) {
    n_sites += seg.size();
  }

  // Build combined Thole interaction matrix A (3*N_sites x 3*N_sites)
  eeInteractor interactor;

  Eigen::MatrixXd A = Eigen::MatrixXd::Zero(3 * n_sites, 3 * n_sites);
  {
    Index i_offset = 0;
    for (const auto& seg_i : polar_segs) {
      Index j_offset = 0;
      for (const auto& seg_j : polar_segs) {
        for (Index i = 0; i < seg_i.size(); ++i) {
          for (Index j = 0; j < seg_j.size(); ++j) {
            Index gi = i_offset + i;
            Index gj = j_offset + j;
            if (gi == gj) {
              // Diagonal block: inverse polarisability tensor
              A.block<3, 3>(3 * gi, 3 * gi) = seg_i[i].getPInv();
            } else if (gi > gj) {
              // Off-diagonal: Thole interaction (symmetric)
              Eigen::Matrix3d T =
                  interactor.FillTholeInteraction(seg_i[i], seg_j[j]);
              A.block<3, 3>(3 * gi, 3 * gj) = T;
              A.block<3, 3>(3 * gj, 3 * gi) = T.transpose();
            }
          }
        }
        j_offset += seg_j.size();
      }
      i_offset += seg_i.size();
    }
  }

  // Factorise A once (LLT: A is positive definite by construction of Thole)
  Eigen::LLT<Eigen::MatrixXd> llt(A);

  // --- Loop over all aux-basis functions mu ---
  // For efficiency, build right-hand-side matrix B (3*N_sites x N_aux)
  // where column mu = field of xi_mu at all MM sites, then solve in one batch.

  Eigen::MatrixXd B = Eigen::MatrixXd::Zero(3 * n_sites, naux);

  Index mu = 0;
  for (const AOShell& shell : auxbasis) {
    for (Index func = 0; func < shell.getNumFunc(); ++func, ++mu) {
      B.col(mu) =
          CalcAuxFunctionField(shell, func, grid, polar_segs);
    }
  }

  // Solve A * Delta_d = -B for all N_aux right-hand sides simultaneously,
  // matching the Cholesky_IntraSegment convention where b = -V = -E.
  // Result: Delta_d (3*N_sites x N_aux), column mu = induced dipoles for xi_mu.
  Eigen::MatrixXd Delta_d = llt.solve(-B);

  // --- Loop over mu again; set induced dipoles and compute V_reac column ---
  mu = 0;
  for (const AOShell& shell : auxbasis) {
    for (Index func = 0; func < shell.getNumFunc(); ++func, ++mu) {

      // Load induced dipoles for this source function into the polar sites
      {
        Index site_idx = 0;
        for (auto& seg : polar_segs) {
          for (auto& site : seg) {
            site.setInduced_Dipole(Delta_d.col(mu).segment<3>(3 * site_idx));
            ++site_idx;
          }
        }
      }

      // Step 2: analytic integral -> column mu of V_reac
      matrix_.col(mu) = CalcDipolePotentialColumn(mu, auxbasis, polar_segs);
    }
  }

  // --- Symmetrize ---
  // In exact arithmetic V_reac is symmetric (the reaction-field kernel
  // v_reac(r,r') = v_reac(r',r)).  Any asymmetry is purely numerical from
  // the grid integration in step 1.  SelfAdjointEigenSolver (used downstream
  // in Pseudo_InvSqrt_GWBSE) requires a symmetric matrix.
  matrix_ = 0.5 * (matrix_ + matrix_.transpose());

  // --- Reset polar sites ---
  for (auto& seg : polar_segs) {
    for (auto& site : seg) {
      site.setInduced_Dipole(Eigen::Vector3d::Zero());
      site.Reset();
    }
  }
}

}  // namespace xtp
}  // namespace votca
