/*
 *            Copyright 2009-2026 The VOTCA Development Team
 *                       (http://www.votca.org)
 *
 *      Licensed under the Apache License, Version 2.0 (the "License")
 *
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *              http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

// Standard includes
#include <cmath>

// Local VOTCA includes
#include "votca/xtp/ewaldrealspaceinteractor.h"

namespace votca {
namespace xtp {

namespace {
constexpr double kRSqrtPi = 0.5641895835477563;  // 1/sqrt(pi)
}  // namespace

EwaldRealSpaceInteractor::BFunctions EwaldRealSpaceInteractor::ComputeB(
    double r) const {
  const double rr1 = 1.0 / r;
  const double rr2 = rr1 * rr1;
  const double a1 = alpha_;
  const double a3 = a1 * a1 * a1;
  const double expTerm = kRSqrtPi * std::exp(-a1 * a1 * r * r);

  BFunctions b;
  b.B0 = std::erfc(a1 * r) * rr1;
  b.B1 = rr2 * (b.B0 + 2.0 * a1 * expTerm);
  b.B2 = rr2 * (3.0 * b.B1 + 4.0 * a3 * expTerm);
  return b;
}

EwaldRealSpaceInteractor::BFunctions EwaldRealSpaceInteractor::ComputeErfB(
    double r) const {
  const BFunctions erfc_b = ComputeB(r);
  const double rr1 = 1.0 / r;
  const double rr3 = rr1 * rr1 * rr1;
  BFunctions b;
  b.B0 = rr1 - erfc_b.B0;
  b.B1 = rr3 - erfc_b.B1;
  b.B2 = 3.0 * rr3 * rr1 * rr1 - erfc_b.B2;
  return b;
}

EwaldRealSpaceInteractor::TholeFactors EwaldRealSpaceInteractor::ComputeThole(
    double r, const PolarSite& site1, const PolarSite& site2) const {
  // Reuses the exponential Thole model already implemented in
  // eeInteractor::FillTholeInteraction, so that the induced-induced
  // damping used here is identical to the one PolarRegion's own
  // finite-region induction solve already uses.
  const double au3 = thole_ * r * r * r * site1.getSqrtInvEigenDamp() *
                     site2.getSqrtInvEigenDamp();
  TholeFactors t{1.0, 1.0};
  if (au3 < 40.0) {
    const double expUa = std::exp(-au3);
    t.l3 = 1.0 - expUa;
    t.l5 = 1.0 - (1.0 + au3) * expUa;
  }
  return t;
}

namespace {

// Potential and field generated by a screened point charge q and dipole mu
// (source), evaluated at a point separated from the source by r_vec
// (pointing from source to target). Field is what a target site
// experiences; the target's own energy contribution is computed by the
// caller from this and the target's own moments.
struct ScreenedPotentialField {
  double phi;
  Eigen::Vector3d field;
};

ScreenedPotentialField EvaluateSource(
    double q, const Eigen::Vector3d& mu, const Eigen::Vector3d& r_vec,
    double r, const EwaldRealSpaceInteractor::BFunctions& b) {
  ScreenedPotentialField result;
  const double mu_dot_r = mu.dot(r_vec);

  // phi(r) = q*B0 + (mu . r_vec)*B1
  result.phi = q * b.B0 + mu_dot_r * b.B1;

  // E(r) = -grad(phi) = q*r_vec*B1 + [(mu.r_vec)*r_vec*B2 - mu*B1]
  // Note: B2 (from ComputeB's recursion) already carries the factor of
  // (2l-1)=3 for l=2, so the r_vec*r_vec dyadic term is (mu.r_vec)*B2,
  // not 3*(mu.r_vec)*B2 -- an earlier version of this file double-counted
  // that factor of 3 and was caught by the dipole-dipole cross-check in
  // test_ewaldrealspaceinteractor.cc.
  result.field = q * b.B1 * r_vec + mu_dot_r * b.B2 * r_vec - b.B1 * mu;
  (void)r;
  return result;
}

}  // namespace

template <class T, enum Estatic CE>
double EwaldRealSpaceInteractor::ApplyStaticField(
    const T& site1, PolarSite& site2,
    const Eigen::Vector3d& source_shift) const {
  const Eigen::Vector3d r_vec =
      site2.getPos() - (site1.getPos() + source_shift);
  const double r = r_vec.norm();
  const BFunctions b = ComputeB(r);

  const double q1 = site1.getCharge();
  const Eigen::Vector3d mu1 = site1.getStaticDipole();
  const ScreenedPotentialField src = EvaluateSource(q1, mu1, r_vec, r, b);

  if (CE == Estatic::noE_V) {
    site2.V_noE() += src.field;
  } else {
    site2.V() += src.field;
  }

  const double q2 = site2.getCharge();
  const Eigen::Vector3d mu2 = site2.getStaticDipole();
  // U = q2*phi1(r2) - mu2.E1(r2)
  return q2 * src.phi - mu2.dot(src.field);
}

template <class T, enum Estatic CE>
void EwaldRealSpaceInteractor::ApplyIntramolecularStaticCorrection(
    const T& site1, PolarSite& site2) const {
  const Eigen::Vector3d r_vec = site2.getPos() - site1.getPos();
  const double r = r_vec.norm();
  const BFunctions b = ComputeErfB(r);

  const double q1 = site1.getCharge();
  const Eigen::Vector3d mu1 = site1.getStaticDipole();
  const ScreenedPotentialField src = EvaluateSource(q1, mu1, r_vec, r, b);

  // Subtracted, not added -- see this method's own header documentation
  // (and legacy EwdInteractor::FP12_ERF_At_By's own explicit "Note the
  // (-)" comment) for why: this removes the reciprocal-space leak for
  // this intramolecular pair, it does not add a genuine field
  // contribution of its own.
  if (CE == Estatic::noE_V) {
    site2.V_noE() -= src.field;
  } else {
    site2.V() -= src.field;
  }
}

template <enum Estatic CE>
double EwaldRealSpaceInteractor::ApplyInducedField(
    const PolarSite& site1, PolarSite& site2,
    const Eigen::Vector3d& source_shift) const {
  const Eigen::Vector3d r_vec =
      site2.getPos() - (site1.getPos() + source_shift);
  const double r = r_vec.norm();
  const BFunctions b = ComputeB(r);
  const TholeFactors t = ComputeThole(r, site1, site2);

  const Eigen::Vector3d mu1 = site1.getInducedDipole();
  const double mu_dot_r = mu1.dot(r_vec);

  // Thole damping is multiplicative on the erfc-screened B-functions, same
  // combination rule as legacy's l3*B1 + l5*B2 (see class documentation).
  // B2 already carries its (2l-1)=3 recursion factor -- see the comment
  // in EvaluateSource (this file) for why there is no separate 3.0* here.
  const Eigen::Vector3d field =
      mu_dot_r * (t.l5 * b.B2) * r_vec - (t.l3 * b.B1) * mu1;

  if (CE == Estatic::noE_V) {
    site2.V_noE() += field;
  } else {
    site2.V() += field;
  }

  const Eigen::Vector3d mu2 = site2.getInducedDipole();
  return -mu2.dot(field);
}

template <class S1, class S2>
double EwaldRealSpaceInteractor::CalcStaticEnergy(const S1& site1,
                                                   const S2& site2) const {
  const Eigen::Vector3d r_vec = site2.getPos() - site1.getPos();
  const double r = r_vec.norm();
  const BFunctions b = ComputeB(r);

  const double q1 = site1.getCharge();
  const Eigen::Vector3d mu1 = site1.getStaticDipole();
  const ScreenedPotentialField src = EvaluateSource(q1, mu1, r_vec, r, b);

  const double q2 = site2.getCharge();
  const Eigen::Vector3d mu2 = site2.getStaticDipole();
  return q2 * src.phi - mu2.dot(src.field);
}

double EwaldRealSpaceInteractor::CalcInducedEnergy(
    const PolarSite& site1, const PolarSite& site2) const {
  const Eigen::Vector3d r_vec = site2.getPos() - site1.getPos();
  const double r = r_vec.norm();
  const BFunctions b = ComputeB(r);
  const TholeFactors t = ComputeThole(r, site1, site2);

  const Eigen::Vector3d mu1 = site1.getInducedDipole();
  const Eigen::Vector3d mu2 = site2.getInducedDipole();
  const double mu1_dot_r = mu1.dot(r_vec);

  const Eigen::Vector3d field1 =
      mu1_dot_r * (t.l5 * b.B2) * r_vec - (t.l3 * b.B1) * mu1;
  return -mu2.dot(field1);
}

// Explicit instantiations for the source types actually used.
template double EwaldRealSpaceInteractor::ApplyStaticField<StaticSite,
                                                            Estatic::V>(
    const StaticSite&, PolarSite&, const Eigen::Vector3d&) const;
template double EwaldRealSpaceInteractor::ApplyStaticField<StaticSite,
                                                            Estatic::noE_V>(
    const StaticSite&, PolarSite&, const Eigen::Vector3d&) const;
template double EwaldRealSpaceInteractor::ApplyStaticField<PolarSite,
                                                            Estatic::V>(
    const PolarSite&, PolarSite&, const Eigen::Vector3d&) const;
template double EwaldRealSpaceInteractor::ApplyStaticField<PolarSite,
                                                            Estatic::noE_V>(
    const PolarSite&, PolarSite&, const Eigen::Vector3d&) const;

template void
EwaldRealSpaceInteractor::ApplyIntramolecularStaticCorrection<StaticSite,
                                                              Estatic::V>(
    const StaticSite&, PolarSite&) const;
template void
EwaldRealSpaceInteractor::ApplyIntramolecularStaticCorrection<
    StaticSite, Estatic::noE_V>(const StaticSite&, PolarSite&) const;
template void
EwaldRealSpaceInteractor::ApplyIntramolecularStaticCorrection<PolarSite,
                                                              Estatic::V>(
    const PolarSite&, PolarSite&) const;
template void
EwaldRealSpaceInteractor::ApplyIntramolecularStaticCorrection<
    PolarSite, Estatic::noE_V>(const PolarSite&, PolarSite&) const;

template double EwaldRealSpaceInteractor::ApplyInducedField<Estatic::V>(
    const PolarSite&, PolarSite&, const Eigen::Vector3d&) const;
template double EwaldRealSpaceInteractor::ApplyInducedField<Estatic::noE_V>(
    const PolarSite&, PolarSite&, const Eigen::Vector3d&) const;

template double EwaldRealSpaceInteractor::CalcStaticEnergy<StaticSite,
                                                            StaticSite>(
    const StaticSite&, const StaticSite&) const;
template double EwaldRealSpaceInteractor::CalcStaticEnergy<StaticSite,
                                                            PolarSite>(
    const StaticSite&, const PolarSite&) const;
template double EwaldRealSpaceInteractor::CalcStaticEnergy<PolarSite,
                                                            StaticSite>(
    const PolarSite&, const StaticSite&) const;
template double EwaldRealSpaceInteractor::CalcStaticEnergy<PolarSite,
                                                            PolarSite>(
    const PolarSite&, const PolarSite&) const;

}  // namespace xtp
}  // namespace votca
