ROOTDIR := ../../scripts

JPGPICS :=
PNGPICS := 
FIGPICS := scheme_t.eps scheme.eps scheme_noCP_noSCF.eps schemes_all.eps
AGRPICS :=
GPPICS  := 
SVGPICS :=
SUBDIRS :=
LOCALCLEAN := figtex2eps-preamble.tex

include ../../Makefile.incl

